### ISSUE TITLE
Desire to help

### ISSUE THREAD

**Issue by gnarmedia** [Doist/reactist#123]
I'd like to show what I can do for Doist by helping on this project, is there any way I can help? I also thinking about using this project on a project I'm working on.

**Comment by henningmu** [comment]
Hi @gnarmedia 
first of all thanks a lot for reaching out and expressing your desire to help us out here.
At the moment I'm more or less maintaining this project on my own. I have all open tasks, ideas and bugs in Todoist. During this week / beginning of next week I'll try to bring them into Github with some more details for you (and maybe others) to pick them up 👍 

I can't confidently say contributing here will give you any bonus credits during our interview process but I guess it's worth a try 😃

**Comment by gnarmedia** [comment]
Awesome! I fully understand that it might not earn me any brownie points, I also just want to contribute more to open source in general and this seem like a good place to start.

As for my own needs, I was looking to add some validation states for inputs, perhaps notifications, that kinda stuff, maybe some more advanced components.

**Comment by henningmu** [comment]
I added some issues that might be a good starting point into the project. Just let me know if you want to work on any of those and: no problem if you don't ;)

I'm a bit hesitant to add new components without a proper spec. Normally, we move components from either [twist](https://twist.com) or [todoist](https://todoist.com) here. So if you see something that you'd like to reuse please feel free to open an issue and we can discuss it in more detail :)

For validation states you can open an issue (so I know what you're working on) and create a PR. Just because we don't use it at the moment doesn't mean it can't be merged here. Good starting points might be the `<Input />` component or `<ErrorMessage />` component.

**Comment by gnarmedia** [comment]
Awesome! Thanks! I'll check it out in more detail when I am at my computer, but these look like a great starting point.
