### ISSUE TITLE
Add an abortable onClose hook to Modal

### ISSUE THREAD

**Issue by vishnugopal** [Doist/reactist#382]
###  🚀 Feature request

Implement an optional `onClose: () => boolean` prop for `Modal.Box`. When it returns false, `_closeModal()` will refuse to close the modal.

Also see (Doist internal link): https://github.com/Doist/twist-web/pull/2881#issuecomment-717916976

### Motivation

There are cases when the ESC key (or any closeModal call) needs to be aborted or changed to a different action (like displaying a parent Modal). An onCloseModal hook that can return false to prevent modal closure (& then implement the custom logic required) will help here!

### Example

```
<Modal.Box onClose={() => false}></Modal.Box>
```

### Possible implementations

This will need a change to Modal.tsx's Box class. If possible, rewrite this in a functional manner too!

**Comment by gnapse** [comment]
Hmmm, my suggestion was that pressing "Escape" when a dropdown was expanded inside a modal should only dismiss the dropdown and not the modal.

I'm not sure if the solution needs to go down this proposed path. I was thinking more in terms of having the dropdowns detect the "Escape" key themselves, dismiss themselves (hide the dropdown), and then maybe call `event.stopPropagation` will take care of making the modal remain and not go way.

What do you think?

**Comment by vishnugopal** [comment]
@gnapse 

Oh what I thought [you mentioned here](https://github.com/Doist/twist-web/pull/2881#issuecomment-717260443) was child modals being closed when ESC key being pressed instead of opening up the parent modal. 

What you mention above is a different issue right?

**Comment by gnapse** [comment]
Oh yes, I thought this was about solving [this other issue I mentioned here](https://github.com/Doist/twist-web/pull/2868#issuecomment-717234741). I see this is about something else.

About this issue: not sure if there's anything too special we need to do in the modal about this issue. The solution I think goes through making pressing "Cancel" and typing "Escape" become two equivalent actions. That is, the modal should work so that pressing "Escape" calls the same handler that's called when clicking "Cancel".

**Comment by vishnugopal** [comment]
@gnapse I agree, but it does require a change in Modal. Currently the code binds a keyhandler in reactist, and then does this:

```js
    _handleKeyDown(event: Partial<KeyboardEvent>) {
        if (event.keyCode === 27) {
            // ESC
            this._closeModal()
            if (event.preventDefault) event.preventDefault()
        }
    }

    _closeModal() {
        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
        const modalElement = document.getElementById('modal_box')!
        ReactDOM.unmountComponentAtNode(modalElement)
    }
```

As you can see, there is no opportunity to hook into or customize this, so we need some kind of callback here!

I somehow missed [this feedback of yours](https://github.com/Doist/twist-web/pull/2868#issuecomment-717234741) entirely! 😷 I'll file todos to go through and get this fixed.

**Comment by gnapse** [comment]
I agree that it requires changes in the modal, but I'd say it requires deeper changes. I think the modal we have in Todoist is much better and should be ported to Reactist, because it does not work the same way.

What I'm trying to say is, the hook proposal is suitable for how the modal currently works, but I'd start by questioning why it works that way, and re-architect it a bit if needed. This behavior should come more naturally without users of the modal having to pass in a hook to prevent it from closing on "Escape:.

**Comment by vishnugopal** [comment]
Understood, let me take a look at the modal in Todoist, and get back to you! 🙌

**Comment by gnapse** [comment]
This is no longer relevant after our newest modal is introduced (see #547) which will land on beta later this week.
